// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellnessClimbingWall.Data;

namespace WellnessClimbingWall.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210225180612_Patron")]
    partial class Patron
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WellnessClimbingWall.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rope")
                        .HasColumnType("int");

                    b.Property<string>("Setter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("Route");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            Color = "Blue",
                            DateCreated = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "5.5",
                            Location = "None",
                            Rope = 21,
                            Setter = "John"
                        },
                        new
                        {
                            RouteId = 2,
                            Color = "Red",
                            DateCreated = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "8.2",
                            Location = "None",
                            Rope = 6,
                            Setter = "Jack"
                        },
                        new
                        {
                            RouteId = 3,
                            Color = "Yellow",
                            DateCreated = new DateTime(2021, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "4.9",
                            Location = "North Wall",
                            Rope = 0,
                            Setter = "Charlie"
                        },
                        new
                        {
                            RouteId = 4,
                            Color = "Black",
                            DateCreated = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = "9.2",
                            Location = "None",
                            Rope = 11,
                            Setter = "Stacy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
